### ISSUE TITLE
Sanitize html

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/berliner#23]
Run all html through a sanitizer with a whitelist of allowed dom objects and classes stripped (?)

**Comment by geoffreylitt** [comment]
It might make sense for this to be in the framework rather than in each individual source, for two reasons:

* protects users from crazy XSS type stuff hidden in a source they're using from someone's repo
* makes it less work to write a source

Part of this might also be just documenting what the expected output of a source is for the body of a post.
