### ISSUE TITLE
Decide on a configuration format

### ISSUE THREAD

**Issue by geoffreylitt** [s3ththompson/berliner#39]

**Comment by geoffreylitt** [comment]
# A sample Berliner config file

Describing a Berliner in a declarative configuration format isn't too bad.

Visually it is a little verbose. Switching from JSON to YAML might help
a bit, but JSON is so widely used that it's probably not worth the cost of
making people learn YAML. I think it would be hard to get much more concise
without considering a real DSL. (Imagine a SQL-like DSL for filters! Not
that I'm really suggesting that, but it would be cool)

One minor weakness of a declarative format is that there's a
natural limit on how flexible you can get with how data flows through the
system. (See the Grunt vs Gulp debate)

This berliner currently only contains filters that are applied to
one source, and filters that are applied to all sources. Getting more
complicated than that in this format (e.g. different chains of filters with
dependencies) might require getting very verbose in a format like this.

```js
{
  sources: [
    // Simple built-in source
    { name: "atlantic" },
    // NYT source with paywall credentials
    {
      name: "new-york-times",
      username: "foo",
      password: "bar",
      // A filter only applied to this specific source:
      // WHERE section == politics AND author != Thomas Friedman
      filters: [
        {
          name: "and",
          filter1: {
            name: "section",
            value: "politics"
          },
          filter2: {
            name: "not",
            filter: {
              name: "author",
              value: "Thomas Friedman"
            }
          }
        }
      ]
    },
    // Custom RSS feed
    {
      name: "rss",
      url: "bar.com/rss.xml",
      filters: [
        { name: "limit", limit: 3 }
      ]
    },
    // Twitter
    { name: "twitter", username: "foo", password: "bar" }
  ],
  // A sequence of filters applied in order to the entire stream.
  filters: [
    {
      name: "dedupe",
      history_file: "~/.berliner/dedupe"
    },
    {
      name: "sort",
      attributes: [
        "source",
        "publish_date"
      ]
    }
  ],
  // The whole stream can be piped to multiple renderers
  // (This might be useful, and also keeps the consistency of each top-level
  // key having an array of objects as theh value)
  renderers: [
    {
      name: "web",
      theme: "minimal",
      port: 3000
    }
  ]
}
```

**Comment by s3ththompson** [comment]
As a contrast to Grunt-style declarative, object-based config, I spent some time working through a Gulp-style functional config.  Here's an initial brainstorm (pasted here for posterity):

```go
import (
	f "berliner/filters"
)

p := f.Filter(articles)
	.Pipe(
		f.Reject(
			func(p berliner.Post) bool {
				return p.Source == "new-york-times" &&
					p.Section == "politics" &&
					p.author == "Thomas Friedman"
			}
		)
	)
	.Pipe(
		f.Dedupe("~/.berliner/dedupe")
	)
	.Pipe(
		f.Sort(["source", "publish_date"])
	).Do()
```

**Comment by s3ththompson** [comment]
Exploring the functional configuration route in more depth:

## 1 Berliner, 4 ways

Okay, let's assemble a small, but reasonably complex Berliner.  My sources are the New York Times arts section (which will require my username and password to scrape), the top posts on Hacker News, and all the links posted to a certain Twitter account.  I'd like to apply a set of filters to them: deduping (dupes ranked higher), adding some sort of metadata, rejecting all NYT articles about film, keeping only "Show HN" HN posts, and restricting the total length of my Berliner to something that can be read in 30 min.  Then, I'd like to render to a PDF called `output.pdf` as well as an HTML file called `output.html` with Bootstrap as the stylesheet.

Here are a few approaches for how to represent this Berliner in code (i.e. a few different Go library APIs).

(Note: each version has a short example in the comments, to show the programming style as purely and succintly as possible.)

### Middleware-inspired
(c.f. [github.com/labstack/echo](https://github.com/labstack/echo))

```go
package main

import (
	"berliner"
	s "berliner/sources"
	f "berliner/filters"
	r "berliner/renderers"
)

/* Ex:
b := berliner.New()
b.Source(s.Source1())
b.Source(s.Source2())
b.Filter(f.Filter1())
b.Filter(f.Filter2())
b.Render(r.Renderer1())
b.Go()
*/

b := berliner.New()
b.Credential(b.NewCred("nytimes.com", "s3ththompson", "passw0rd"))

b.Source(s.Twitter("s3ththompson"))
// storing return is optional, but useful for applying source-specific filters later
nyt := b.Source(s.NewYorkTimes("arts"))
hn := b.Source(s.HackerNews())

nyt.Filter(f.Reject(f.TagsInclude("film")))
// assuming we don't expose a TitleIncludes() builtin conditional, I'd have to write a custom function for this
hn.Filter(f.Pick(func(post berliner.Post) bool {
	return strings.HasPrefix(post.Title, "Show HN:")
})))
b.Filter(f.Dedupe("dedupe-db.txt", true)) // true, for boosting ranking of dupes
b.Filter(f.SortBy("rank"))
b.Filter(f.ReadTime(30))
b.Filter(f.AddMetadata())

b.Render(r.PDF("output.pdf"))
b.Render(r.HTML("output.html", "bootstrap.css"))

err := b.Go() // just renders to specified output files
err := b.GoRead() // renders and opens a web browser to read
if err != nil {
	panic("Berliner error: ", err)
}
```

- *Pros*: very clear, very readable; fairly idiomatic Go; top-level vs. source-specific `Filter()` method solves source-specific filters in a predictable way.
- *Cons*: applying filters to any sub-grouping of sources is impossible; repeatedly calling register methods is fairly verbose; relying on order of method calling for order of filters feels slightly flimsy; poor error handling since you don't see any errors until the end

(Note: actually, it may be possible to evaluate filters/sources at the time they're registered, thus providing the ability to return errors immediately after each line)
 
### Gulp-inspired
(c.f. [github.com/gulpjs/gulp](https://github.com/gulpjs/gulp))

```go
package main

import (
	"berliner"
	s "berliner/sources"
	f "berliner/filters"
	r "berliner/renderers"
)

/* Ex:
b := berliner.New()
b.Source(s.Source1(), s.Source2()).Pipe(f.Filter1()).Pipe(f.Filter2()).Pipe(r.Renderer1())
*/

b := berliner.New([b.NewCred("nytimes.com", "s3ththompson", "passw0rd")])

nyt, err := b.Source(
		s.NewYorkTimes("arts")
	).Pipe(
		f.Reject(f.TagsInclude("film"))
	)
if err != nil {
	panic("New York Times error: ", err)
}
hn, err := b.Source(
		s.HackerNews()
	).Pipe(
		f.Pick(func(post berliner.Post) bool {
			return strings.HasPrefix(post.Title, "Show HN:")
		})
	)
if err != nil {
	panic("Hacker News error: ", err)
}

posts, err := b.Concat(
		nyt,
		hn,
		b.Source(s.Twitter("s3ththompson")
	).Pipe(
		f.Dedupe("dedupe-db.txt", true)
	).Pipe(
		f.SortBy("rank")
	).Pipe(
		f.ReadTime(30)
	).Pipe(
		f.AddMetadata()
	)
if err != nil {
	panic("Filtering error: ", err)
}

rendered, err := posts.Pipe(
		r.PDF("output.pdf")
	).Pipe(
		r.HTML("output.html", "bootstrap.css")
	)
if err != nil {
	panic("Rendering error: ", err)
}

rendered.Read() // opens a web browser to read
```
- *Pros*: extremely expressive (full control over what filters get applied to what posts); familiar to Gulp/JavaScript developers; ability to read errors at any step in the chain; best representation of our mental model of Berliner so far
- *Cons*: Not very idiomatic Go; more difficult to read since Go doesn't allow you to put line-breaks between method calls (i.e. before the `.`); chainable methods require returning entire state with each call

### Data-centric

```go
package main

import (
	"berliner"
	s "berliner/sources"
	f "berliner/filters"
	r "berliner/renderers"
)

/* Ex:
b := &berliner.Berliner{
	sources: [
		s.Source1(),
		s.Source2(),
	],
	filters: [
		f.Filter1(),
		f.Filter2(),
	],
	renderers: [
		r.Renderer1(),
	],
}
b.Go()
*/

b := &berliner.Berliner{
	creds: [
		b.NewCred("nytimes.com", "s3ththompson", "passw0rd"),
	],
	sources: [
		s.NewYorkTimes("arts"),
		s.HackerNews(),
		s.Twitter("s3ththompson"),
	],
	filters: [
		f.Only("new-york-times", f.Reject(f.TagsInclude("film")))), // `f.Only()` restricts filter to specified source
		f.Only("hacker-news", f.Pick(func(post berliner.Post) bool {
			return strings.HasPrefix(post.Title, "Show HN:")
		}))),
		f.Dedupe("dedupe-db.txt", true),
		f.SortBy("rank"),
		f.ReadTime(30),
		f.AddMetadata(),
	],
	renderers: [
		r.PDF("output.pdf"),
		r.HTML("output.html", "bootstrap.css"),
	],
}
err := b.Go()
err := b.GoRead()
if err != nil {
	panic("Berliner error: ", err)
}
```
- *Pros*: very simple for simple Berliners, easily translate to DSL / static config; `struct`-centric part is idiomatic Go, filter order is very clear
- *Cons*: complex filter logic requires backflips around weird conditionals disguised as builtin methods; complex filter conditionals are not idiomatic Go; doesn't allow complex chains of logic; poor error handling since you don't see any errors until the end

### DIY

```go
package main

import (
	"berliner/browser"
	s "berliner/sources"
	f "berliner/filters"
	r "berliner/renderers"
)

/* Ex:
b := browser.New()
s1_posts := s.Source1().Fetch(browser)
s2_posts := s.Source2().Fetch(browser)
posts = append(s1_posts, s2_posts)
posts := f.Filter1().Filter(posts)
posts := f.Filter2().Filter(posts)
r.Renderer1().Render(posts)
*/

b := browser.New(&browser.Cred{
	domain: "nytimes.com",
	username: "s3ththompson",
	password: "passw0rd",
})

t_posts, err := s.Twitter("s3ththompson").Fetch(b)
nyt_posts, err := s.NewYorkTimes("arts").Fetch(b)
hn_posts, err := s.HackerNews().Fetch(b)
if err != nil {
	panic("Fetch error: ", err)
}

nyt_posts, err = f.Reject(f.TagsInclude("film")).Filter(nyt_posts)
hn_posts, err = f.Pick(func(post berliner.Post) bool {
	return strings.HasPrefix(post.Title, "Show HN:")
})).Filter(hn_posts)
if err != nil {
	panic("Filter error: ", err)
}
posts = append(t_posts, nyt_posts, hn_posts)


posts, err = f.Dedupe("dedupe-db.txt", true).Filter(posts)
posts, err = f.SortBy("rank")
posts, err = f.ReadTime(30).Filter(posts)
posts, err = f.AddMetadata().Filter(posts)
if err != nil {
	panic("Filter error: ", err)
}

err := r.PDF(posts, "output.pdf")
if err != nil {
	panic("PDF rendering error: ", err)
}
err := r.HTML(posts, "output.pdf", "bootstrap.css")
if err != nil {
	panic("PDF rendering error: ", err)
}
```

- *Pros*: idiomatic Go; fairly readable; clear error handling; very expressive; do-it-yourself
- *Cons*: not very user-friendly; no attempt made at simplifying programming model; requires Go knowlege; do-it-yourself

### Functional 😜

```go
b := HTML("output.html", "bootstrap.css", 
	PDF("output.pdf",
			AddMetadata(
				ReadTime(30,
					Dedupe("dedupe-db.txt", true,
						// abbreviated
						Sources(
							NewYorkTimes("arts"), HackerNews(), Twitter("s3ththompson")
						))))));
```

- *Pros*: it's functional
- *Cons*: it's functional

**Comment by s3ththompson** [comment]
For the moment, we've decided to go with Middleware-style functional config.  Closing the issue for now, to be re-opened when we consider higher-level configuration methods.
